### PR TITLE
Delete whole date files

### PR DESCRIPTION
**Pull request by Eb-Zeero**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-database/242)

### CODE REVIEW

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-database/242)* status: 1 of 3 files reviewed, 5 unresolved discussions (waiting on @hettlage)

___
*[src/ssda/ssda_delete.py, line 36 at r1](https://reviewable.io/reviews/saltastroops/data-archive-database/242#-MEvNPJlA7DnlesbGaUE:-MFUl7dL9bZr5qSAANfz:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-database/blob/96a22ec39c219808d9e200d07a9fe747532459ab/src/ssda/ssda_delete.py#L36)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'd suggest to name the option --file-path, as underscores in option names are unusual.
</blockquote></details>

Done.
___
*[src/ssda/ssda_delete.py, line 74 at r1](https://reviewable.io/reviews/saltastroops/data-archive-database/242#-MEvNLSH2JfVTNBdgviu:-MFUfO6M2yb0w9jBtSsd:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-database/blob/96a22ec39c219808d9e200d07a9fe747532459ab/src/ssda/ssda_delete.py#L74)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'd suggest to output to stdout.
</blockquote></details>

Done.
___
*[src/ssda/ssda_delete.py, line 76 at r1](https://reviewable.io/reviews/saltastroops/data-archive-database/242#-MEwlJRO-5Tg8N4UTcg8:-MFUfQPP0jlZ72S6J_wU:b32wsm) ([raw file](https://github.com/saltastroops/data-archive-database/blob/96a22ec39c219808d9e200d07a9fe747532459ab/src/ssda/ssda_delete.py#L76)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Might be obsolete when outputting to stdout, but just in case: lYou probably have to use writeline; I'd guess that writelines creates a single character per line if called with a string rather than list.
</blockquote></details>

no
___
*[src/ssda/ssda_delete.py, line 76 at r1](https://reviewable.io/reviews/saltastroops/data-archive-database/242#-MEwlYzWDg2MqsKA5yUa:-MFUfS22DdDoSRaBi40_:b-9goqcv) ([raw file](https://github.com/saltastroops/data-archive-database/blob/96a22ec39c219808d9e200d07a9fe747532459ab/src/ssda/ssda_delete.py#L76)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You should output the file path rather than obs id.
</blockquote></details>

sorry wrong variable naming
___
*[src/ssda/ssda_delete.py, line 77 at r1](https://reviewable.io/reviews/saltastroops/data-archive-database/242#-MEwjmkGCR8xDk1xEZz7:-MFUl4vv-j2BzJ2iH6AC:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-database/blob/96a22ec39c219808d9e200d07a9fe747532459ab/src/ssda/ssda_delete.py#L77)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe better:

"The delete command does not support deleting files for a date range, as there might be cases where this leads to unexpected results.

Your chosen date range covers the following file paths. Please check the list and call the delete command with the --file-path option for every path you want to delete."
</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-database/242)* status: all files reviewed, 16 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[src/ssda/ssda_delete.py, line 76 at r1](https://reviewable.io/reviews/saltastroops/data-archive-database/242#-MEwlJRO-5Tg8N4UTcg8:-MF_4S8EEt_FvItL5pHi:b4cfb3c) ([raw file](https://github.com/saltastroops/data-archive-database/blob/96a22ec39c219808d9e200d07a9fe747532459ab/src/ssda/ssda_delete.py#L76)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

no
</blockquote></details>

True, it doesn't. I did some digging:  The reason is that `writelines` doesn't add line separators. But I'm quite sureit  will still interpret every single character as a line of its own. I'd suggest to use the write method instead.
___
*[src/ssda/ssda_delete.py, line 24 at r3](https://reviewable.io/reviews/saltastroops/data-archive-database/242#-MF_-yQnC9a6Fh78Xk3m:-MF_-yQoDOWoxTcwYbRA:b-6yghio) ([raw file](https://github.com/saltastroops/data-archive-database/blob/68ef6a8d391b5fb463d7b5cdfdff96c88aeb7d72/src/ssda/ssda_delete.py#L24)):*
> ```Python
> ):
>     if not fits and not start and not end:
>         raise ValueError("You must provide either a file path or a date range.")
> ```

file path ---> FITS file path

[as there are two file paths now]
___
*[src/ssda/ssda_delete.py, line 27 at r3](https://reviewable.io/reviews/saltastroops/data-archive-database/242#-MF_0E-L3JGTJNwy_n2G:-MF_0E-L3JGTJNwy_n2H:bs8n7ex) ([raw file](https://github.com/saltastroops/data-archive-database/blob/68ef6a8d391b5fb463d7b5cdfdff96c88aeb7d72/src/ssda/ssda_delete.py#L27)):*
> ```Python
>     if fits and (start or end):
>         raise ValueError("You cannot provide provide both a file path and a date range.")
>     if out and (start or end):
> ```

out ---> not out
___
*[src/ssda/ssda_delete.py, line 28 at r3](https://reviewable.io/reviews/saltastroops/data-archive-database/242#-MF_0OXy7Q6cNh38Qldr:-MF_0OXy7Q6cNh38Qlds:bv7ypfy) ([raw file](https://github.com/saltastroops/data-archive-database/blob/68ef6a8d391b5fb463d7b5cdfdff96c88aeb7d72/src/ssda/ssda_delete.py#L28)):*
> ```Python
>         raise ValueError("You cannot provide provide both a file path and a date range.")
>     if out and (start or end):
>         raise ValueError("--out to log affected files needs to be provided for a date range.")
> ```

"The --out option must be used with the --start and --end option."
___
*[src/ssda/ssda_delete.py, line 30 at r3](https://reviewable.io/reviews/saltastroops/data-archive-database/242#-MF_0W8Y6UYmLP8LfbE1:-MF_0W8Y6UYmLP8LfbE2:b-h1e4fy) ([raw file](https://github.com/saltastroops/data-archive-database/blob/68ef6a8d391b5fb463d7b5cdfdff96c88aeb7d72/src/ssda/ssda_delete.py#L30)):*
> ```Python
>         raise ValueError("--out to log affected files needs to be provided for a date range.")
>     if fits and out:
>         raise ValueError("--out will have no affect since you are deleting a single file.")
> ```

"The --fits and --out options cannot be used together."
___
*[src/ssda/ssda_delete.py, line 39 at r3](https://reviewable.io/reviews/saltastroops/data-archive-database/242#-MF_1bH13q-XSeU-rK6C:-MF_1bH13q-XSeU-rK6D:bki5jne) ([raw file](https://github.com/saltastroops/data-archive-database/blob/68ef6a8d391b5fb463d7b5cdfdff96c88aeb7d72/src/ssda/ssda_delete.py#L39)):*
> ```Python
> 
> def delete_in_ssda(file: Optional[str], start: Optional[date], end: Optional[date]):
>     validate_options(filename=file, start=start, end=end)
> ```

There has been a conflict here, so the code has changed. But it was missing the out parameter before already, it seems.
___
*[src/ssda/ssda_delete.py, line 62 at r3](https://reviewable.io/reviews/saltastroops/data-archive-database/242#-MF_29As9TUVjP2brVel:-MF_29As9TUVjP2brVem:b1or9c8) ([raw file](https://github.com/saltastroops/data-archive-database/blob/68ef6a8d391b5fb463d7b5cdfdff96c88aeb7d72/src/ssda/ssda_delete.py#L62)):*
> ```Python
>             )
>             ssda_database_service.commit_transaction()
>             logging.info(msg="\nSuccessfully deleted observation")
> ```

Maybe the add : for {fits}
___
*[src/ssda/ssda_delete.py, line 65 at r3](https://reviewable.io/reviews/saltastroops/data-archive-database/242#-MF_2LPx9dyIxt5hraaS:-MF_2LPx9dyIxt5hraaT:bp37dca) ([raw file](https://github.com/saltastroops/data-archive-database/blob/68ef6a8d391b5fb463d7b5cdfdff96c88aeb7d72/src/ssda/ssda_delete.py#L65)):*
> ```Python
>         else:
>             if start is None:
>                 raise ValueError("The start date is None.")
> ```

is None --> must not be None
___
*[src/ssda/ssda_delete.py, line 67 at r3](https://reviewable.io/reviews/saltastroops/data-archive-database/242#-MF_2UYaCSf50fk-Sm3O:-MF_2UYaCSf50fk-Sm3P:bp37dca) ([raw file](https://github.com/saltastroops/data-archive-database/blob/68ef6a8d391b5fb463d7b5cdfdff96c88aeb7d72/src/ssda/ssda_delete.py#L67)):*
> ```Python
>                 raise ValueError("The start date is None.")
>             if end is None:
>                 raise ValueError("The end date is None.")
> ```

is None --> must not be None
___
*[src/ssda/ssda_delete.py, line 72 at r3](https://reviewable.io/reviews/saltastroops/data-archive-database/242#-MF_2Y_73W9WzVjzqY1k:-MF_2Y_73W9WzVjzqY1l:bn6w0ox) ([raw file](https://github.com/saltastroops/data-archive-database/blob/68ef6a8d391b5fb463d7b5cdfdff96c88aeb7d72/src/ssda/ssda_delete.py#L72)):*
> ```Python
>                 nights=DateRange(parse_date(start, now), parse_date(end, now))
>             )
>             files_affected = open(f"{out}", "w")
> ```

I'd suggest to use open with a `with` block.
___
*[src/ssda/ssda_delete.py, line 78 at r3](https://reviewable.io/reviews/saltastroops/data-archive-database/242#-MF_6NdB4MOX4-oLqcD5:-MF_6NdB4MOX4-oLqcD6:b5e9qgm) ([raw file](https://github.com/saltastroops/data-archive-database/blob/68ef6a8d391b5fb463d7b5cdfdff96c88aeb7d72/src/ssda/ssda_delete.py#L78)):*
> ```Python
>                              f"cases where this leads to unexpected results.\n\n"
>                              f"Your chosen date range covers the following file paths. Please check the list and call "
>                              f"the delete command with the --fits option for every path you want to delete.")
> ```

Maybe you should add where to find the list, as it is not logged? :) [Or remove this logging message and instead add it to the output file?]
___
*[src/ssda/database/ssda.py, line 318 at r3](https://reviewable.io/reviews/saltastroops/data-archive-database/242#-MF_6uNFBlIz3jdabyFX:-MF_6uNFBlIz3jdabyFY:b-36lvub) ([raw file](https://github.com/saltastroops/data-archive-database/blob/68ef6a8d391b5fb463d7b5cdfdff96c88aeb7d72/src/ssda/database/ssda.py#L318)):*
> ```Python
>                 return None
> 
>     def find_affected_file_paths(self, nights: types.DateRange, ) -> List[str]:
> ```

find_affected_file_paths ---> find_file_paths
___
*[src/ssda/database/ssda.py, line 320 at r3](https://reviewable.io/reviews/saltastroops/data-archive-database/242#-MF_7B3K-wgFjPtmKsL4:-MF_7B3K-wgFjPtmKsL5:bxvlsfg) ([raw file](https://github.com/saltastroops/data-archive-database/blob/68ef6a8d391b5fb463d7b5cdfdff96c88aeb7d72/src/ssda/database/ssda.py#L320)):*
> ```Python
>     def find_affected_file_paths(self, nights: types.DateRange, ) -> List[str]:
>         """
>         The observation file paths that are observed in a date range. The start date and the end date are inclusive.
> ```

are observed ---> have been observed

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-database/242)* status: all files reviewed, 16 unresolved discussions (waiting on @hettlage)

___
*[src/ssda/ssda_delete.py, line 76 at r1](https://reviewable.io/reviews/saltastroops/data-archive-database/242#-MEwlJRO-5Tg8N4UTcg8:-MFa7A7u2lpPUnW0CDIN:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-database/blob/96a22ec39c219808d9e200d07a9fe747532459ab/src/ssda/ssda_delete.py#L76)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

True, it doesn't. I did some digging:  The reason is that `writelines` doesn't add line separators. But I'm quite sureit  will still interpret every single character as a line of its own. I'd suggest to use the write method instead.
</blockquote></details>

Done.
___
*[src/ssda/ssda_delete.py, line 24 at r3](https://reviewable.io/reviews/saltastroops/data-archive-database/242#-MF_-yQnC9a6Fh78Xk3m:-MFa4Mqa-E000WrVd5y1:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-database/blob/68ef6a8d391b5fb463d7b5cdfdff96c88aeb7d72/src/ssda/ssda_delete.py#L24)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

file path ---> FITS file path

[as there are two file paths now]
</blockquote></details>

Done.
___
*[src/ssda/ssda_delete.py, line 27 at r3](https://reviewable.io/reviews/saltastroops/data-archive-database/242#-MF_0E-L3JGTJNwy_n2G:-MFa4YRg68stx5ph2Mtj:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-database/blob/68ef6a8d391b5fb463d7b5cdfdff96c88aeb7d72/src/ssda/ssda_delete.py#L27)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

out ---> not out
</blockquote></details>

Done.
___
*[src/ssda/ssda_delete.py, line 28 at r3](https://reviewable.io/reviews/saltastroops/data-archive-database/242#-MF_0OXy7Q6cNh38Qldr:-MFa4g1cDICCiA1mLEIW:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-database/blob/68ef6a8d391b5fb463d7b5cdfdff96c88aeb7d72/src/ssda/ssda_delete.py#L28)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

"The --out option must be used with the --start and --end option."
</blockquote></details>

Done.
___
*[src/ssda/ssda_delete.py, line 30 at r3](https://reviewable.io/reviews/saltastroops/data-archive-database/242#-MF_0W8Y6UYmLP8LfbE1:-MFa4np3-WvWmDl1v1Nl:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-database/blob/68ef6a8d391b5fb463d7b5cdfdff96c88aeb7d72/src/ssda/ssda_delete.py#L30)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

"The --fits and --out options cannot be used together."
</blockquote></details>

Done.
___
*[src/ssda/ssda_delete.py, line 39 at r3](https://reviewable.io/reviews/saltastroops/data-archive-database/242#-MF_1bH13q-XSeU-rK6C:-MFaAYhc0379wqlor9zW:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-database/blob/68ef6a8d391b5fb463d7b5cdfdff96c88aeb7d72/src/ssda/ssda_delete.py#L39)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

There has been a conflict here, so the code has changed. But it was missing the out parameter before already, it seems.
</blockquote></details>

Done.
___
*[src/ssda/ssda_delete.py, line 62 at r3](https://reviewable.io/reviews/saltastroops/data-archive-database/242#-MF_29As9TUVjP2brVel:-MFa5P856cgl6gY12jch:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-database/blob/68ef6a8d391b5fb463d7b5cdfdff96c88aeb7d72/src/ssda/ssda_delete.py#L62)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe the add : for {fits}
</blockquote></details>

Done.
___
*[src/ssda/ssda_delete.py, line 65 at r3](https://reviewable.io/reviews/saltastroops/data-archive-database/242#-MF_2LPx9dyIxt5hraaS:-MFa5atJ2uekby8zOqy5:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-database/blob/68ef6a8d391b5fb463d7b5cdfdff96c88aeb7d72/src/ssda/ssda_delete.py#L65)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

is None --> must not be None
</blockquote></details>

Done.
___
*[src/ssda/ssda_delete.py, line 67 at r3](https://reviewable.io/reviews/saltastroops/data-archive-database/242#-MF_2UYaCSf50fk-Sm3O:-MFa5bDkBEeXMdoHlCvd:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-database/blob/68ef6a8d391b5fb463d7b5cdfdff96c88aeb7d72/src/ssda/ssda_delete.py#L67)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

is None --> must not be None
</blockquote></details>

Done.
___
*[src/ssda/ssda_delete.py, line 72 at r3](https://reviewable.io/reviews/saltastroops/data-archive-database/242#-MF_2Y_73W9WzVjzqY1k:-MFa6fkF4s3I-1LyhUOM:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-database/blob/68ef6a8d391b5fb463d7b5cdfdff96c88aeb7d72/src/ssda/ssda_delete.py#L72)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'd suggest to use open with a `with` block.
</blockquote></details>

Done.
___
*[src/ssda/ssda_delete.py, line 78 at r3](https://reviewable.io/reviews/saltastroops/data-archive-database/242#-MF_6NdB4MOX4-oLqcD5:-MFa7nOL-4rcfPC5mqLR:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-database/blob/68ef6a8d391b5fb463d7b5cdfdff96c88aeb7d72/src/ssda/ssda_delete.py#L78)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe you should add where to find the list, as it is not logged? :) [Or remove this logging message and instead add it to the output file?]
</blockquote></details>

Done.
___
*[src/ssda/database/ssda.py, line 318 at r3](https://reviewable.io/reviews/saltastroops/data-archive-database/242#-MF_6uNFBlIz3jdabyFX:-MFa66-E-bmb7mEn7bGy:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-database/blob/68ef6a8d391b5fb463d7b5cdfdff96c88aeb7d72/src/ssda/database/ssda.py#L318)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

find_affected_file_paths ---> find_file_paths
</blockquote></details>

Done.
___
*[src/ssda/database/ssda.py, line 320 at r3](https://reviewable.io/reviews/saltastroops/data-archive-database/242#-MF_7B3K-wgFjPtmKsL4:-MFa5v4u1bRAAXi8zmSa:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-database/blob/68ef6a8d391b5fb463d7b5cdfdff96c88aeb7d72/src/ssda/database/ssda.py#L320)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

are observed ---> have been observed
</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-database/242)* status: all files reviewed, 12 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[src/ssda/cli.py, line 77 at r4](https://reviewable.io/reviews/saltastroops/data-archive-database/242#-MFaBYg7DzFzw6uQ7rM2:-MFaBYg7DzFzw6uQ7rM3:bb0qey2) ([raw file](https://github.com/saltastroops/data-archive-database/blob/f5264f2706f47c567a677f7a6cc02ff48d26172e/src/ssda/cli.py#L77)):*
> ```Python
> )
> @click.option(
>     "--out", help="Output file for affected fits file.",
> ```

Output file for the list of commands to execute for removing all observations in a date range.
___
*[src/ssda/ssda_delete.py, line 24 at r3](https://reviewable.io/reviews/saltastroops/data-archive-database/242#-MF_-yQnC9a6Fh78Xk3m:-MFaCT1dDnFwIDng50LL:by8pr4n) ([raw file](https://github.com/saltastroops/data-archive-database/blob/68ef6a8d391b5fb463d7b5cdfdff96c88aeb7d72/src/ssda/ssda_delete.py#L24)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see a change?
___
*[src/ssda/ssda_delete.py, line 27 at r3](https://reviewable.io/reviews/saltastroops/data-archive-database/242#-MF_0E-L3JGTJNwy_n2G:-MGxVOad0dSjGO517WSu:by8pr4n) ([raw file](https://github.com/saltastroops/data-archive-database/blob/68ef6a8d391b5fb463d7b5cdfdff96c88aeb7d72/src/ssda/ssda_delete.py#L27)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see a change?
___
*[src/ssda/ssda_delete.py, line 28 at r3](https://reviewable.io/reviews/saltastroops/data-archive-database/242#-MF_0OXy7Q6cNh38Qldr:-MGxVZf9BTc5HBAdMO7H:by8pr4n) ([raw file](https://github.com/saltastroops/data-archive-database/blob/68ef6a8d391b5fb463d7b5cdfdff96c88aeb7d72/src/ssda/ssda_delete.py#L28)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see a change?
___
*[src/ssda/ssda_delete.py, line 30 at r3](https://reviewable.io/reviews/saltastroops/data-archive-database/242#-MF_0W8Y6UYmLP8LfbE1:-MGxVclb5cItcrs1M80K:b7frh8j) ([raw file](https://github.com/saltastroops/data-archive-database/blob/68ef6a8d391b5fb463d7b5cdfdff96c88aeb7d72/src/ssda/ssda_delete.py#L30)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don;t see a change?
___
*[src/ssda/ssda_delete.py, line 73 at r4](https://reviewable.io/reviews/saltastroops/data-archive-database/242#-MGxWWXY7RUx3fFFajns:-MGxWWXY7RUx3fFFajnt:b-d3n96a) ([raw file](https://github.com/saltastroops/data-archive-database/blob/f5264f2706f47c567a677f7a6cc02ff48d26172e/src/ssda/ssda_delete.py#L73)):*
> ```Python
>                 nights=DateRange(parse_date(start, now), parse_date(end, now))
>             )
>             with open(f"{out}", "w") as files_affected:
> ```

Maybe f rather than files_affected? (It's really an output file, not a list of affected files.) But if you disagree, just say "won't fix".
___
*[src/ssda/ssda_delete.py, line 76 at r4](https://reviewable.io/reviews/saltastroops/data-archive-database/242#-MGxXIPb9HdC6TdquYmr:-MGxXIPb9HdC6TdquYms:bkj3wmy) ([raw file](https://github.com/saltastroops/data-archive-database/blob/f5264f2706f47c567a677f7a6cc02ff48d26172e/src/ssda/ssda_delete.py#L76)):*
> ```Python
>                 for obs_path in observation_paths:
>                     files_affected.write("ssda delete -fits " + obs_path + "\n")
>             logging.info(msg=f"The affected files can be found on the output file: {out}")
> ```

on the ---> in the
___
*[src/ssda/database/ssda.py, line 320 at r3](https://reviewable.io/reviews/saltastroops/data-archive-database/242#-MF_7B3K-wgFjPtmKsL4:-MGxX0pM2Po4NYSbFvB8:b-naj5up) ([raw file](https://github.com/saltastroops/data-archive-database/blob/68ef6a8d391b5fb463d7b5cdfdff96c88aeb7d72/src/ssda/database/ssda.py#L320)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thinking about it... Maybe better: The file paths for the observations made in a date range.

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-database/242)* status: 1 of 4 files reviewed, 12 unresolved discussions (waiting on @hettlage)

___
*[src/ssda/cli.py, line 77 at r4](https://reviewable.io/reviews/saltastroops/data-archive-database/242#-MFaBYg7DzFzw6uQ7rM2:-MHp7lxCDq9G8fgSvTTQ:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-database/blob/f5264f2706f47c567a677f7a6cc02ff48d26172e/src/ssda/cli.py#L77)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Output file for the list of commands to execute for removing all observations in a date range.
</blockquote></details>

Done.
___
*[src/ssda/ssda_delete.py, line 24 at r3](https://reviewable.io/reviews/saltastroops/data-archive-database/242#-MF_-yQnC9a6Fh78Xk3m:-MHBGve23Vuyo8Rh7J9e:bb6un1j) ([raw file](https://github.com/saltastroops/data-archive-database/blob/68ef6a8d391b5fb463d7b5cdfdff96c88aeb7d72/src/ssda/ssda_delete.py#L24)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't see a change?
</blockquote></details>

Done
___
*[src/ssda/ssda_delete.py, line 27 at r3](https://reviewable.io/reviews/saltastroops/data-archive-database/242#-MF_0E-L3JGTJNwy_n2G:-MHBH8piElA3nRtsJ1cx:b-q55nog) ([raw file](https://github.com/saltastroops/data-archive-database/blob/68ef6a8d391b5fb463d7b5cdfdff96c88aeb7d72/src/ssda/ssda_delete.py#L27)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't see a change?
</blockquote></details>

sorry done now
___
*[src/ssda/ssda_delete.py, line 28 at r3](https://reviewable.io/reviews/saltastroops/data-archive-database/242#-MF_0OXy7Q6cNh38Qldr:-MHBHVRu5jPmXvrGpN0I:bmqamy4) ([raw file](https://github.com/saltastroops/data-archive-database/blob/68ef6a8d391b5fb463d7b5cdfdff96c88aeb7d72/src/ssda/ssda_delete.py#L28)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't see a change?
</blockquote></details>

What was going on about this
___
*[src/ssda/ssda_delete.py, line 30 at r3](https://reviewable.io/reviews/saltastroops/data-archive-database/242#-MF_0W8Y6UYmLP8LfbE1:-MHBHiJbDjCwiIRV0GYD:blp6g5w) ([raw file](https://github.com/saltastroops/data-archive-database/blob/68ef6a8d391b5fb463d7b5cdfdff96c88aeb7d72/src/ssda/ssda_delete.py#L30)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don;t see a change?
</blockquote></details>

but what was going on with this updates
___
*[src/ssda/ssda_delete.py, line 73 at r4](https://reviewable.io/reviews/saltastroops/data-archive-database/242#-MGxWWXY7RUx3fFFajns:-MHBI-oV3tIbXMdAP8Oo:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-database/blob/f5264f2706f47c567a677f7a6cc02ff48d26172e/src/ssda/ssda_delete.py#L73)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe f rather than files_affected? (It's really an output file, not a list of affected files.) But if you disagree, just say "won't fix".
</blockquote></details>

Done.
___
*[src/ssda/ssda_delete.py, line 76 at r4](https://reviewable.io/reviews/saltastroops/data-archive-database/242#-MGxXIPb9HdC6TdquYmr:-MHBK2as0ORDFpjVAM3j:by7cofq) ([raw file](https://github.com/saltastroops/data-archive-database/blob/f5264f2706f47c567a677f7a6cc02ff48d26172e/src/ssda/ssda_delete.py#L76)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

on the ---> in the
</blockquote></details>

not apllicable anymore

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-database/242)* status: 1 of 4 files reviewed, 12 unresolved discussions (waiting on @hettlage)

___
*[src/ssda/database/ssda.py, line 320 at r3](https://reviewable.io/reviews/saltastroops/data-archive-database/242#-MF_7B3K-wgFjPtmKsL4:-MIrmmFQCbbtx11b-UY9:bvinr5) ([raw file](https://github.com/saltastroops/data-archive-database/blob/68ef6a8d391b5fb463d7b5cdfdff96c88aeb7d72/src/ssda/database/ssda.py#L320)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Thinking about it... Maybe better: The file paths for the observations made in a date range.
</blockquote></details>

this was done before 
for got to click done

**Review by hettlage — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r5, 2 of 2 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-database/242#-:-MIsB-GT8hMGZ-K7VA2h:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
