### PR TITLE
Daily update subcommand (and fixing formatting/linting issues)

### PR DESCRIPTION
**Pull request by hettlage**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-database/250)

### CODE REVIEW

**Review by Eb-Zeero — CHANGES_REQUESTED** [review]
> Reviewed 10 of 24 files at r2.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-database/250)* status: 10 of 24 files reviewed, 1 unresolved discussion (waiting on @Eb-Zeero and @hettlage)

___
*[setup.cfg, line 21 at r2](https://reviewable.io/reviews/saltastroops/data-archive-database/250#-MGrflMm4wBmOEWrl_FY:-MGrflMm4wBmOEWrl_FZ:b-uqbsdv) ([raw file](https://github.com/saltastroops/data-archive-database/blob/b268da2f6a24180f5a37b3455ca6dd271ccc02a4/setup.cfg#L21)):*
> ```INI
> [flake8]
> max-line-length = 89
> ignore = E501,W503
> ```

don't you need to comment what these are

**Review by Eb-Zeero — COMMENTED** [review]
> Reviewed 13 of 24 files at r2.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-database/250)* status: 23 of 24 files reviewed, 1 unresolved discussion (waiting on @Eb-Zeero and @hettlage)

**Review by hettlage — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-database/250)* status: 18 of 24 files reviewed, 1 unresolved discussion (waiting on @Eb-Zeero)

___
*[setup.cfg, line 21 at r2](https://reviewable.io/reviews/saltastroops/data-archive-database/250#-MGrflMm4wBmOEWrl_FY:-MHuG46b1KvoKYc7uBpK:b-ih9r8w) ([raw file](https://github.com/saltastroops/data-archive-database/blob/b268da2f6a24180f5a37b3455ca6dd271ccc02a4/setup.cfg#L21)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

don't you need to comment what these are
</blockquote></details>

Moved configuration to its own config file; dropped ignore line.

**Review by Eb-Zeero — DISMISSED** [review]
> Reviewed 7 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-database/250)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by Eb-Zeero — APPROVED** [review]
> Reviewed 4 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-database/250)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
