### PR TITLE
Simplified data request

### PR DESCRIPTION
**Pull request by Lonwabo11**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-database/254)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-database/254)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @Lonwabo11)

___
*[sql/V8__simplified_data_requests.sql, line 3 at r1](https://reviewable.io/reviews/saltastroops/data-archive-database/254#-MGi5vxK6nPXt9XzBbMP:-MGi5vxLCNVvA4aUom7_:bxn1t9w) ([raw file](https://github.com/saltastroops/data-archive-database/blob/4c9565eecc282d947cc9bd3aa3df1799bbd4a6be/sql/V8__simplified_data_requests.sql#L3)):*
> ```TSQL
> SET search_path TO admin;
> 
> DROP TABLE data_request_status;
> ```

You should drop the columns first (to avoid errors caused by foreign keys). Actually, you might have to delete indexes for the dropped columns as well.
___
*[sql/V8__simplified_data_requests.sql, line 5 at r1](https://reviewable.io/reviews/saltastroops/data-archive-database/254#-MGi6MAN7qgBtkVTyvoX:-MGi6MAN7qgBtkVTyvoY:b4901yy) ([raw file](https://github.com/saltastroops/data-archive-database/blob/4c9565eecc282d947cc9bd3aa3df1799bbd4a6be/sql/V8__simplified_data_requests.sql#L5)):*
> ```TSQL
> DROP TABLE data_request_status;
> 
> ALTER TABLE  data_request DROP COLUMN path, data_request_status_id;
> ```

Should be: ALTER TABLE  data_request DROP COLUMN path, DROP COLUMN data_request_status_id;

**Review by hettlage — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-database/254)* status: all files reviewed, 2 unresolved discussions (waiting on @Lonwabo11)

**Review by Lonwabo11 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-database/254)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @hettlage)

___
*[sql/V8__simplified_data_requests.sql, line 3 at r1](https://reviewable.io/reviews/saltastroops/data-archive-database/254#-MGi5vxK6nPXt9XzBbMP:-MGmMmY3E_DuiPYtcOPL:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-database/blob/4c9565eecc282d947cc9bd3aa3df1799bbd4a6be/sql/V8__simplified_data_requests.sql#L3)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You should drop the columns first (to avoid errors caused by foreign keys). Actually, you might have to delete indexes for the dropped columns as well.
</blockquote></details>

Done.
___
*[sql/V8__simplified_data_requests.sql, line 5 at r1](https://reviewable.io/reviews/saltastroops/data-archive-database/254#-MGi6MAN7qgBtkVTyvoX:-MGmMn001XaLCGlKHZLh:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-database/blob/4c9565eecc282d947cc9bd3aa3df1799bbd4a6be/sql/V8__simplified_data_requests.sql#L5)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Should be: ALTER TABLE  data_request DROP COLUMN path, DROP COLUMN data_request_status_id;
</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]

**Review by Lonwabo11 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-database/254)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @hettlage)

___
*[sql/V8__simplified_data_requests.sql, line 1 at r2](https://reviewable.io/reviews/saltastroops/data-archive-database/254#-MGcPSZpSDHzs4vGowT_-r2-1:-MHCAdwi6ix_6fUJyin1:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-database/blob/8f827f0f627ab524b84910b7fe7a125f115ad6e5/sql/V8__simplified_data_requests.sql#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The search path is set (permanently) in a previous Flyway file. So re-setting it here (and limiting it to admin) might cause surprises in future. I'd remove the line.
</blockquote></details>

Done.

**Review by hettlage — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-database/254)* status: all files reviewed, 3 unresolved discussions (waiting on @hettlage)

**Review by hettlage — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-database/254)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by hettlage — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-database/254)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
